[package]
name = "log-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
anyhow = "1.0.95"
rayon = "1.10.0"
regex = "1.10"
chrono = "0.4"
indicatif = "0.17.11"
tempfile = "3.16.0"
